top:
  map_frame: "map"
  helpers:
    frame:      
      mesh: "frame"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [-0.5, 0.0, 0.0, 0.0, 0.0, 3.1415]
      scale: [0.1, 0.1, 0.1]
  tiles:
    tile0:
      mesh: "tile_l"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, 1.5707]
      scale: [0.5, 0.5, 0.5]
    tile1:
      mesh: "tile_l"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [.3038, 0.0, 0.0, 0.0, 0.0, 1.5707]
      scale: [0.5, 0.5, 0.5]
    tile2:
      mesh: "tile_T"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, .3038, 0.0, 0.0, 0.0, 3.1415]
      scale: [0.5, 0.5, 0.5]
    tile3:
      mesh: "tile_X"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.3038, .3038, 0.0, 0.0, 0.0, 0.0]
      scale: [0.5, 0.5, 0.5]
  tape_configurations:
    T:
      strip1:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [-0.07595, 0.0, 0.008, 0.0, 0.0, 0.0]
        scale: [0.5, 1.0, 1.0]
      strip2:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [0.0, 0.0, 0.008, 0.0, 0.0, 1.5707]
        scale: [1.0, 1.0, 1.0]
    X:
      strip1:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [0.0, 0.0, 0.007, 0.0, 0.0, 0.0]
        scale: [1.0, 1.0, 1.0]
      strip2:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [0.0, 0.0, 0.007, 0.0, 0.0, 1.5707]
        scale: [1.0, 1.0, 1.0]
    l:
      strip1:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [0.0, 0.0, 0.007, 0.0, 0.0, 0.0]
        scale: [1.0, 1.0, 1.0]
  desitnations:
    dest_1:
      pose: [0.0, 0.0, 0.007, 0.0, 0.0, 0.0]
      scale: [0.0, 0.0, 0.0]
  robots:
    robot0:
      frame: "robot0_base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot1:
      frame: "robot1_base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot2:
      frame: "robot3_base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot3:
      frame: "robot4_base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot4:
      frame: "robot5_base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot5:
      frame: "robot6_base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot6:
      frame: "robot2_base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robotdummy:
      frame: "robotdummy_base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]



