top:
  map_frame: "map"
  helpers:
    frame:      
      mesh: "frame"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [-0.5, 0.0, 0.0, 0.0, 0.0, 3.1415]
      scale: [0.1, 0.1, 0.1]
  tiles:
    tile0:
      mesh: "tile_l"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, 1.5707]
      scale: [0.5, 0.5, 0.5]
    tile1:
      mesh: "tile_l"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [.3038, 0.0, 0.0, 0.0, 0.0, 1.5707]
      scale: [0.5, 0.5, 0.5]
    tile2:
      mesh: "tile_T"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, .3038, 0.0, 0.0, 0.0, 3.1415]
      scale: [0.5, 0.5, 0.5]
    tile3:
      mesh: "tile_X"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.3038, .3038, 0.0, 0.0, 0.0, 0.0]
      scale: [0.5, 0.5, 0.5]
  tape_configurations:
    T:
      strip1:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [-0.07595, 0.0, 0.008, 0.0, 0.0, 0.0]
        scale: [0.5, 1.0, 1.0]
      strip2:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [0.0, 0.0, 0.008, 0.0, 0.0, 1.5707]
        scale: [1.0, 1.0, 1.0]
    X:
      strip1:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [0.0, 0.0, 0.007, 0.0, 0.0, 0.0]
        scale: [1.0, 1.0, 1.0]
      strip2:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [0.0, 0.0, 0.007, 0.0, 0.0, 1.5707]
        scale: [1.0, 1.0, 1.0]
    l:
      strip1:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [0.0, 0.0, 0.007, 0.0, 0.0, 0.0]
        scale: [1.0, 1.0, 1.0]
    r:
      strip1:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [-0.07595, 0.0, 0.008, 0.0, 0.0, 0.0]
        scale: [0.5, 1.0, 1.0]
      strip2:
        mesh: "tape"
        color: [0.2, 0.2, 0.2, 1.0]
        pose: [0.0, -0.07595, 0.008, 0.0, 0.0, 1.5707]
        scale: [0.5, 1.0, 1.0]
    spur_supplimental:
      color: [0.2, 0.2, 0.2, 1.0]
  destination_config:
    scale: [0.25, 0.25, 0.015]
    pose: [0.0, 0.0, 0.008, 0.0, 0.0, 0.0]
    color: [0.6, 0.0, 0.0, 0.4]

  desitnations:
    dest_1:
      pose: [0.0, 0.0, 0.007, 0.0, 0.0, 0.0]
      scale: [0.0, 0.0, 0.0]
  robots:
    robot0:
      frame: "Robot0base"
      mesh: "amr"
      color: [0.8, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot1:
      frame: "Robot1base"
      mesh: "amr"
      color: [1.0, 0.8, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot2:
      frame: "Robot3base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot3:
      frame: "Robot4base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot4:
      frame: "Robot5base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot5:
      frame: "Robot6base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robot6:
      frame: "Robot2base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]
    robotdummy:
      frame: "Robotdummy_base"
      mesh: "amr"
      color: [1.0, 1.0, 1.0, 1.0]
      pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.5707]
      scale: [0.8, 0.8, 0.8]



